### ISSUE TITLE
Footer contents and layout

### ISSUE THREAD

**Issue by lougroshek** [spinnaker/spinnaker.io#16]
> Implement updated CDF-standard footer and push to a repo in the CDF org

^I might need a bit more information for this task.

Are the current footer contents what is wanted there, or something different? If so, will there be a design spec?

**Comment by brian-armory** [comment]
@dnilasor can you clarify the footer requirements?

**Comment by dnilasor** [comment]
I've reviewed other CDF footers and pinged the Linux Foundation for requirements and any standardization underway. 

FWIW, of we all like Tekton's footer best of the CDF projects:

![image](https://user-images.githubusercontent.com/36797588/89347963-95ffdf80-d660-11ea-8505-4a708608cbe5.png)

tekton.io

I will re: this when I hear back from Brian

**Comment by dnilasor** [comment]
Here's that site, maybe you can lift something from it https://github.com/tektoncd/website

**Comment by dnilasor** [comment]
Got a re: from the CDF that I tagged you in, https://github.com/cdfoundation/foundation/issues/211

Let's go with something like the Tekton footer using the artwork and sample text that Brian provided in that issue please. Thanks @amygroshek
