### ISSUE TITLE
Escaping errors seen in links

### ISSUE THREAD

**Issue by sonnyvan** [spinnaker/spinnaker.io#185]
Links seem to have escaping errors. 

For example: if you visit https://spinnaker.io/docs/setup/install/providers/kubernetes-v2/k8s-provider/ you will see the following:
![Screen Shot 2022-03-01 at 2 51 02 PM](https://user-images.githubusercontent.com/9056113/156262363-b7829b6e-8e00-4e84-a2ad-54b300e8b1ff.png)
![Screen Shot 2022-03-01 at 2 51 07 PM](https://user-images.githubusercontent.com/9056113/156262373-a18bc1dd-bee0-4120-975e-70a29db8d167.png)

**Comment by kskewes-sf** [comment]
We discovered recently that link apostrophe's and other characters need to be escaped with `\`.
See: https://github.com/spinnaker/spinnaker.io/pull/201/files#diff-da149601addb46d3ccb7e84e9a3f7ef7b7375976b363b892e682180db7239bd1R17

If anyone has time to PR fixes in we can quickly check and merge. :)

**Comment by link108** [comment]
Thank you for the report @sonnyvan 🙏  This has been fixed, so I'm closing the issue
