### ISSUE TITLE
Community Calendar

### ISSUE THREAD

**Issue by lougroshek** [spinnaker/spinnaker.io#19]
> Implement community calendar page linked to Google Calendar

- What's the GCal source for this? 
- Where will this be located on the site?

**Comment by dnilasor** [comment]
on the community landing page is my vote. 

here's the calendar source for the SIG meeting calendar use this for now https://calendar.google.com/calendar/b/3/embed?showPrint=0&showCalendars=0&mode=AGENDA&height=500&wkst=1&bgcolor=%23FFFFFF&src=spinnaker.io_tr65rjf5mfij7p6vucprkhulcc%40group.calendar.google.com&color=%2342104A
