### ISSUE TITLE
Landing page layout

### ISSUE THREAD

**Issue by lougroshek** [spinnaker/spinnaker.io#2]
> Enable card layout and update content block styling in theme

Landing page layout. Mockup here: https://docs.google.com/drawings/d/1FCzzvnK0a-_dQ5Nn1T4jz4DrXfr4tMzc9BrObMdEw3k/edit

Are there more specs for the styling?

**Comment by amygroshek** [comment]
@dnilasor For the roles blocks on the front page cards, what will those link to? Individual web pages for each role? Wondering whether that content should be housed in the /content or /data directories.

**Comment by brian-armory** [comment]
Hi @amygroshek, sorry for the late reply. Things have been hectic as Spinnaker is having a hackathon this week and next!

To answer your question, we'd like the information in the card to be sourced from /data but have the card link to a page(s) in /content. If it's not possible to have the whole card be the link, we can just manually add it to the string in /data.

Correct me if I'm mistaken @dnilasor

**Comment by dnilasor** [comment]
Thanks for your work & patience @amygroshek ! @brian-armory you are not mistaken except, I thought we had a plan to encapsulate all the content these link out to section anchor links on the Getting Started page. Just as likely _I'm_ mistaken
