### ISSUE TITLE
Companies using Spinnaker

### ISSUE THREAD

**Issue by lougroshek** [spinnaker/spinnaker.io#21]
> Implement new “companies using Spinnaker” logo area with all logos in community and success stories
> Make logos clickable, linking to case study, testimonial, or video content

- Which of the above do you want? Whichever is available for the given org?
- Is the intent here to have unique *pages* that house the details of each testimonial/company using Spinnaker? What would the preferred UX be like? 
- Will this content still appear in the docs/community section and the Success Stories page, or is it being consolidated to the home page?

**Comment by dnilasor** [comment]
- Yes, we'll need to link to whichever is available for the given org, but there's definitely considerations to be made case-by-case on which materials are the *best* to share. I can advise on case-by-case basis if that isn't infuriating?
- I think have a dedicated area to house the content may not be sustainable atp (let's double-check that with the team). Probably better to link out to PDF case studies (like success stories page currently does), youtube Videos, and blog articles on the (medium) community blog
- Let's remove this from the docs/commu

**Comment by amygroshek** [comment]
- items in a list in `data` dir
- flags for case studies and testimonials
- flag to hide an item from all lists
- flag for featured content
