### ISSUE TITLE
Scrolling page TOC in docs pages

### ISSUE THREAD

**Issue by lougroshek** [spinnaker/spinnaker.io#22]
1. The current docs page TOC scrolls with the page content until the footer is reached. Will it do what you need or should I make more modifications. 

<img width="1333" alt="Screen Shot 2020-06-21 at 9 45 58 PM" src="https://user-images.githubusercontent.com/746182/85243864-9b82cc80-b408-11ea-86e3-457b4425b6a0.png">

2. There are also some links above the page contents menu: Edit page, create documentation issue, create project issue. Would you like to keep those or remove them?

**Comment by aimeeu** [comment]
- consensus to move edit this page, create docs issue, create project issue to bottom of page
- stylistically de-emphasize the github links
