### ISSUE TITLE
Getting Started page layout

### ISSUE THREAD

**Issue by lougroshek** [spinnaker/spinnaker.io#3]
Getting Started page custom layout. Content dependency.

**Comment by dnilasor** [comment]
Discussed this with @aimeeu and @brian-armory . We are thinking of the following scheme:

- create a splashier landing page for "Getting Started" navigation routing with space for adding some abbreviated content/links in each persona's area. This will be somewhat similar to the cards on the home page (in that those will link directly to many of the same resources that this GS page links to), but there is room for more content on a page than in a card. 
- create a dedicated page for each persona. The dev persona pages will be docs-style, but the 'CXO' page will need to have a lot less text. Areas for bulleted content, some images, and a featured video spot would be great (calling out that this is scope creep!! it's ok with Armory).

This way, folks will get "routed" from the home page hopefully, but if they don't and click on Getting Started instead, they will still be able to explore content that relates to their persona.
