### ISSUE TITLE
Versions document and group are out of date

### ISSUE THREAD

**Issue by stewartmiles** [spinnaker/spinnaker.io#307]
Would it make sense to either delete or redirect folks away from https://spinnaker.io/docs/releases/versions/ and https://groups.google.com/g/spinnaker-announce since they're both way out of date?

**Comment by dbyron-sf** [comment]
What part of the site are you suggesting to change?  Plus also, https://spinnaker.io/docs/releases/versions/ seems up to date to me.  What's out of date about it?

**Comment by stewartmiles** [comment]
@dbyron-sf the last stable release was

```
Latest stable
1.29.2
Released: 2022-12-09 00:03:29 +0000 UTC [Changelog](https://spinnaker.io/changelogs/1.29.2-changelog/)
```

i.e there hasn't been a release for 2 months or so?

**Comment by stewartmiles** [comment]
Ok I've been digging through the docs and I see 2 months ~8 weeks between releases which is about on time for Spinnaker. I noticed that the release calendar hasn't been updated for the next release though. 

To give some background, Google [disabled legacy auth for GKE clusters](https://cloud.google.com/blog/products/containers-kubernetes/kubectl-auth-changes-in-gke) on Friday breaking our Spinnaker instance. I quickly had a dig around to see whether Spinnaker had been patched, it had in https://github.com/spinnaker/clouddriver/pull/5847 with ports to release branches 1.26, 1.27, 1.28 and 1.29 as referenced by https://github.com/spinnaker/spinnaker/issues/6782 . So I quickly upgraded our cluster to 1.29.2 using Halyard 1.54.0 and after inspecting the container the `gke-gcloud-auth-plugin` was not present. When I landed on https://spinnaker.io/docs/releases/versions/ I saw 1.29.2 was released in Dec '22 so I 🤦🏽 and dug around for a release with the patch I need and found nothing but dev releases so I assumed - since this breaks all GKE clusters - that the release must be somewhere but it isn't documented. It seems things are all just broken on a stable release for us GKE users at the moment so we'll need to pull a dev / nightly release.

**Comment by dbyron-sf** [comment]
Correct.  We were planning to release 1.27.next, etc yesterday but maven central was down.  Even so, 2 months is too long.  We're also trying to gather more hands to share the work of releasing new versions...If we're very lucky, 1.30.0 is coming soon too.

I didn't realize this GKE breakage was so severe.  I'll try to accelerate all of this, though realistically 1.29.3 may not happen til next week.

**Comment by stewartmiles** [comment]
FYI: For those who stumble upon this via a search engine, I manually fixed our cluster by upgrading to a pre-released clouddriver image:

```bash
kubectl -n spinnaker get deployment/spin-clouddriver -o yaml | \
  sed -r 's!(image: +)(.*)!\1 us-docker.pkg.dev/spinnaker-community/docker/clouddriver:5.78.3-dev-release-1.29.x-34a37b644-202302152149-unvalidated-ubuntu!' > \
  spin-clouddriver.yaml && kubectl -n spinnaker apply -f spin-clouddriver.yaml
```

I look forward to a new official release 😄
