### ISSUE TITLE
Install and Configure Spinnaker

### ISSUE THREAD

**Issue by Mlibohova** [spinnaker/spinnaker.io#384]
I want to install Halyard but I don't see the official image on docker. Is there a specific registry you guys are on?

docker run -p 8084:8084 -p 9000:9000 \
    --name halyard --rm \
    -v ~/.hal:/home/spinnaker/.hal \
    -it \
    us-docker.pkg.dev/spinnaker-community/docker/halyard:stable

Running this I get random community images

**Comment by dbyron-sf** [comment]
```
$ docker pull us-docker.pkg.dev/spinnaker-community/docker/halyard:1.61.0
```
works for me.
