### ISSUE TITLE
Remove the TOC markdown code that was used for Jekyll

### ISSUE THREAD

**Issue by lougroshek** [spinnaker/spinnaker.io#5]
Docsy also automatically renders a list of contents for each directory with an `_index.*` file in the `./contents` dir. So where pages have a table of contents written into the landing page that TOC could be removed. (This would make the docs easier to maintain in the long run.)

**Comment by brian-armory** [comment]
@amygroshek should I be doing the cleanup in the `v1.19` folder? It looks like `v1.20` is empty.

**Comment by amygroshek** [comment]
@brian-armory Thanks for checking in about that. I just pushed up a commit that removes the versioning directories from `./content/docs`. That should make more sense.
