### ISSUE TITLE
Build fails

### ISSUE THREAD

**Issue by brian-armory** [spinnaker/spinnaker.io#61]
Hi @lougroshek, something in this commit `136a55eebc2c916892659c8dd05cc6f5aec22519` broke the builds cause the alert shortcode can't be found:

```
!136a55e ~/spinnaker.io> hugo serve
Built in 249 ms
Error: Error building site: "/Users/brianle/spinnaker.io/content/en/docs/reference/artifacts-with-artifactsrewrite/types/git-repo/_index.md:8:1": failed to extract shortcode: template for shortcode "alert" not found
```

**Comment by lougroshek** [comment]
@brian-armory I see several successful builds after that commit. 
![Uploading Screen Shot 2020-09-28 at 2.31.05 PM.png…]()

**Comment by lougroshek** [comment]
@brian-armory Fixing your yaml frontmatter entries results in a successful branch build. See [dd20e5f](https://github.com/spinnaker/spinnaker.io/commit/dd20e5f357d16f4d69de86728207e95794ccb512).

<img width="1354" alt="Screen Shot 2020-09-28 at 2 49 02 PM" src="https://user-images.githubusercontent.com/746182/94479029-c57f2400-0199-11eb-9ae2-971d0d56e412.png">

**Comment by brian-armory** [comment]
Hmm, maybe I FUBAR'd my local copy of the repo. When I try to build master locally, I am still getting the error:

```
master ~/spinnaker.io> hugo serve
Built in 180 ms
Error: Error building site: "/Users/brianle/spinnaker.io/content/en/docs/reference/artifacts-with-artifactsrewrite/types/git-repo/_index.md:8:1": failed to extract shortcode: template for shortcode "alerts" not found
```

Let me just delete my repo and clone it again.

**Comment by brian-armory** [comment]
Deleting my repo and recloning it fixed it 😬 I wonder what I FUBAR'd. Thanks for the quick response @lougroshek!
