### ISSUE TITLE
Document shortcodes not rendered by Goldmark

### ISSUE THREAD

**Issue by lougroshek** [spinnaker/spinnaker.io#7]
Provide a list of the things not getting rendered by goldmark. The Spinnaker docs SIG members will review and let you know what can get ripped out.

### `toc`

I'm assuming we can remove this shortcode because docsy inserts a TOC at the bottom of each page that is an _index.md file and has children.

```
{% include toc %}
```

### `spinnaker_user`

```
{% include spinnaker_user id="adevinta_user" %} {% include spinnaker_user id="airbnb_user" %} {% include spinnaker_user id="alto_user" %}
```

### A bunch of what appears to be fetched branch status data on the build status page

http://localhost:1313/docs/v1.19/community/contributing/build-statuses/

```
{% for branch in page.branches %} {%- capture subject -%}{{branch | capitalize}}{%- endcapture -%} {%- if branch == “master” -%} {%- capture job -%}Flow_BuildAndValidate{%- endcapture -%} {%- else -%} {%- capture job -%}Flow_BuildAndValidate_{{branch | remove: “release-” | replace: “.", “_"}}{%- endcapture -%} {%- endif -%}
```

### Additional attributes on anchor tags

```
:style="height: 25px”}{:target=”_blank”} {% endfor %}
```

### Mermaid Charts and Graphs

We *could* add mermaidJS to the theme which would hopefully resolve this, I'm assuming that the Jekyll site was not using server-side Mermaid processing... 

```
graph TB
deck(Deck) –> gate; api(Custom Script/API Caller) –> gate(Gate); gate –> kayenta(Kayenta); gate –> orca(Orca); gate –> clouddriver(Clouddriver); orca –> clouddriver; gate –> rosco(Rosco); orca –> front50; orca –> rosco; gate –> front50(Front50); gate –> fiat(Fiat); orca –> kayenta; clouddriver –> fiat; orca –> fiat; front50 –> fiat; echo(Echo) –> orca; echo –> front50; gate –> echo; gate –> igor(Igor); igor(Igor) –> echo;

hal(Halyard CLI) –> halyard(Halyard Daemon);

classDef default fill:#d8e8ec,stroke:#39546a; linkStyle default stroke:#39546a,stroke-width:1px,fill:none;

classDef halStyle fill:#eebb3c,stroke:#39546a; class halyard,hal halStyle;

classDef external fill:#c0d89d,stroke:#39546a; class deck,api external;

{% include mermaid %}
```

## Built-In Docsy Alternatives 

Docsy Shortcodes are documented [here](https://www.docsy.dev/docs/adding-content/shortcodes/#alert). In particular the `alert` and `pageinfo` shortcodes may be of use.

**Comment by brian-armory** [comment]
Images:

```
{%
  include
  figure
```
- I'm replacing these with the Hugo shortcode{{< figure >}}. Why port something custom when something OOTB does the same thing. 

Images using the `![](/path/file)` syntax, I"m leaving alone since they should show up fine in Hugo.
