### ISSUE TITLE
Mobile navigation menu gets cut off

### ISSUE THREAD

**Issue by nikema-armory** [spinnaker/spinnaker.io#92]
The menu is not completely accessible on the smallest screens. We need a new implementation of a mobile navigation

**Comment by aimeeu** [comment]
@nikema-armory Changing mobile navigation rendering would be an update to the theme or Bootstrap. 
What screen size? According to Google Analytics, the site is primarily accessed from desktops, so we may not have to support the smallest phone screen (ie iPhone 5).  Of the mobile uses who have accessed the site, I didn't see any small phones.

**Comment by nikema-armory** [comment]
> @nikema-armory Changing mobile navigation rendering would be an update to the theme or Bootstrap.
> What screen size? According to Google Analytics, the site is primarily accessed from desktops, so we may not have to support the smallest phone screen (ie iPhone 5). Of the mobile uses who have accessed the site, I didn't see any small phones.

It has already been modified and maybe that's the issue. I can try to revert back to the out-of-the-box navigation.
